export default function TermsOfService() {
  return (
    <div className="policy-page">
      <h1>Terms of Service</h1>
      <p className="policy-date">Last updated: January 2025</p>

      <p>
        Welcome to Thrift Trip. By accessing or using our service, you agree to be bound by these Terms 
        of Service. Please read them carefully before using the platform.
      </p>

      <h2>1. Nature of the Service</h2>
      <p>
        Thrift Trip is a travel search aggregator. We search publicly available flight and hotel pricing data 
        through third-party APIs and display aggregated results to help users identify potential travel options. 
        <strong> Thrift Trip is not a travel agency, booking agent, or airline/hotel reservation system.</strong>
      </p>
      <p>
        When you click "Book Flight" or "Book Hotel," you are redirected to third-party platforms (Google Flights, 
        Google Hotels) where you will complete any booking directly with those services. Thrift Trip is not 
        a party to any booking transaction.
      </p>

      <h2>2. Price Accuracy Disclaimer</h2>
      <p>
        Flight and hotel prices displayed on Thrift Trip are estimates retrieved from third-party APIs at the 
        time of your search. <strong>Prices are subject to change without notice and are not guaranteed.</strong> 
        Factors that may affect actual pricing include:
      </p>
      <ul>
        <li>Fare fluctuations between search and booking</li>
        <li>Seat and room availability at time of booking</li>
        <li>Taxes, fees, and surcharges not included in displayed prices</li>
        <li>Currency conversion rates</li>
        <li>API data delays or inaccuracies from our data providers</li>
      </ul>
      <p>
        Always verify current prices and availability directly on the booking platform before making any 
        financial decisions. The displayed "grand total" is an estimate combining flight prices, hotel rates, 
        and AI-generated activity cost estimates — actual costs will vary.
      </p>

      <h2>3. AI-Generated Content</h2>
      <p>
        Activity cost estimates and travel itineraries are generated by Google Gemini, an artificial intelligence 
        service. This content is provided for informational and planning purposes only. AI-generated estimates 
        may be inaccurate, outdated, or not representative of actual costs in specific locations. Thrift Trip 
        makes no warranty regarding the accuracy of AI-generated content.
      </p>

      <h2>4. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by applicable law, Thrift Trip and its operators are not liable for:
      </p>
      <ul>
        <li>Any losses arising from booking decisions made based on prices displayed on this platform</li>
        <li>Inaccuracies in flight, hotel, or activity cost information</li>
        <li>Service interruptions, API failures, or technical errors</li>
        <li>Actions of third-party booking platforms</li>
        <li>Any indirect, incidental, or consequential damages</li>
      </ul>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use automated tools, scrapers, or bots to access the service at scale</li>
        <li>Attempt to circumvent rate limiting or other technical safeguards</li>
        <li>Use the service in any way that violates applicable laws</li>
        <li>Reverse engineer or attempt to extract proprietary data from the service</li>
      </ul>

      <h2>6. Rate Limiting</h2>
      <p>
        To maintain service availability for all users, we enforce rate limits of 20 requests per IP address 
        per 15-minute window. Excessive use may result in temporary service restrictions.
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        The Thrift Trip name, logo, and original content are protected by copyright. Flight and hotel data 
        displayed through our service is sourced from third-party APIs and is subject to those providers' 
        terms of service.
      </p>

      <h2>8. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms of Service at any time. Continued use of the service 
        after changes are posted constitutes acceptance of the revised terms.
      </p>

      <h2>9. Governing Law</h2>
      <p>
        These Terms shall be governed by the laws of the jurisdiction in which the service operator is 
        located, without regard to conflict of law provisions.
      </p>

      <h2>10. Contact</h2>
      <p>
        For questions about these Terms of Service, contact us at legal@thrifttrip.app.
      </p>
    </div>
  );
}
